// Generated by Bisonc++ V6.04.01 on Tue, 19 Apr 2022 00:07:00 +0530

#ifndef Parser_h_included
#define Parser_h_included

// $insert baseclass
#include "parserbase.h"
// $insert scanner.h
#include "../scanner/scanner.h"
#include <numbers>


class Parser: public ParserBase
{
    // $insert scannerobject
    Scanner d_scanner;
        
    public:
        Parser() = default;
        int parse();

    private:
        void error();                   // called on (syntax) errors
        int lex();                      // returns the next token from the
                                        // lexical scanner. 
        void print();                   // use, e.g., d_token, d_loc
        void exceptionHandler(std::exception const &exc);

    // support functions for parse():
        void executeAction_(int ruleNr);
        void errorRecovery_();
        void nextCycle_();
        void nextToken_();
        void print_();
    
    // consts
        static constexpr double pi();
        static constexpr double exp();
};

constexpr double Parser::pi()
{
    return std::pi;
}

constexpr double Parser::exp()
{
    return std::e;
}

#endif
